### ISSUE TITLE
Error executing 'CREATE FUNCTION

### ISSUE THREAD

**Issue by kusmierz** [clearflask/clearflask#131]
Hi, I can see the following errors in the logs:

```
Error executing 'CREATE FUNCTION vote_wilson
(...)
END  ' (line 34): FUNCTION vote_wilson already exists
Error executing 'CREATE FUNCTION exp_decay
(...)
END  ' (line 21): FUNCTION exp_decay already exists
```

Is this something I should be worried about?

**Comment by matusfaro** [comment]
Which DB are you using with Clearflask? Are you using the [self-host docker compose file](https://github.com/clearflask/clearflask/blob/master/clearflask-release/src/main/docker/compose/docker-compose.self-host.yml)?

Those functions are used for calculating Reddit-like ordering of comments based on votes and time since comment creation. I believe upvoting and downvoting will be broken without these.

**Comment by kusmierz** [comment]
yes, I'm using docker compose file with minor modifications:

```yaml
  mysql-db:
    image: mariadb:lts
    restart: unless-stopped
    command:
      - 'mysqld'
      - '--port=3306'
      - '--sql-mode=IGNORE_SPACE'
      - '--explicit-defaults-for-timestamp'
      - '--secure-file-priv=/tmp'
```

Sorry for the oversight, but I only included part of the error message in my previous message (edited it now). The most important part I left out was the `FUNCTION... already exists` message...
