### ISSUE TITLE
I hope to use reverse proxy to deploy the website, but I don't know how to configure it

### ISSUE THREAD

**Issue by XJY00** [clearflask/clearflask#157]
Describe your issue here

---

I use ClearFlask on:

- [x] Self-hosted (Own domain)
- [ ] Cloud (clearflask.com)
- [ ] Haven't tried (yet)

My financial contributions to ClearFlask:

- [x] I use a free Plan
- [ ] Thinking about it
- [ ] Monthly / Yearly Plan
- [ ] Lifetime Plan

If I want to reverse proxy a domain name and use a reverse proxy server to implement HTTPS, 
how should I fill out the configuration file?
Should I modify some incorrect configurations?
Please help me

my config:
```
{
    "connectToken": "xxx",
    "disableAutoFetchCertificate": true,
    "forceRedirectHttpToHttps": false,
    "parentDomain": "do.xx.com",
    "apiBasePath": "http://localhost:8080"
}

```

connet error: Oops, something went wrong
```
Error: connect ECONNREFUSED 127.0.0.1:8080
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8080
}
```

# Type in your domain
com.smotana.clearflask.web.Application$Config.domain=do.xx.com

```
## SPDX-FileCopyrightText: 2019-2022 Matus Faro <matus@smotana.com>
## SPDX-License-Identifier: Apache-2.0
version: '3.8'
volumes:
  data:
    driver: local
services:
  clearflask-connect:
    image: cf-connet
    depends_on:
      - clearflask-server
    ports:
      - 9080:9080
      - 9443:9443
    environment:
      - NODE_ENV=production
      - ENV=selfhost
      - CLEARFLASK_CREATE_CONNECT_CONFIG_IF_MISSING=1
    volumes:
      - ./connect:/opt/clearflask/
  clearflask-server:
    image: cf-server
    ports:
      - 8080:8080
      # JMX
      - 9950:9950
      - 9951:9951
    environment:
      - CLEARFLASK_ENVIRONMENT=PRODUCTION_SELF_HOST
      - CLEARFLASK_CREATE_SERVER_CONFIG_IF_MISSING=1
    volumes:
      - ./server:/opt/clearflask/
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/health" ]
      interval: 5s
      timeout: 15s
      retries: 2
  # MySQL (enabled by default as an alternative to ElasticSearch)
  mysql-db:
    image: sql-5.7
    platform: linux/amd64
    command:
      - 'mysqld'
      - '--port=3306'
      - '--sql-mode=IGNORE_SPACE'
      - '--explicit-defaults-for-timestamp'
      - '--secure-file-priv=/tmp'
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 13306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=clearflask
  localstack:
    profiles:
      - with-deps
    image: localstack
    expose:
      - 4566
      - 4571
    environment:
      - DEFAULT_REGION=us-east-1
      - LOCALSTACK_HOSTNAME=localstack
      - HOSTNAME_EXTERNAL=localstack
      - SERVICES=dynamodb,ses,s3
      - LS_LOG=warn
      - START_WEB=0
      - USE_SSL=0
      - FORCE_NONINTERACTIVE=true
      - DATA_DIR=/tmp/localstack/data
      - LEGACY_PERSISTENCE=1
    volumes:
      - ./data/localstack:/tmp/localstack
```
